version: "3.9"
services:
  flaskapp:
    build: .
    ports:
      - "5000:5000"
    volumes: 
     - .:/app/
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: database
      SECRET_KEY: SECRET_KEY
